create table if not exists public.electrical_companies (
    company_id bigint generated by default as identity primary key,
    name text not null,
    brand text,
    electrician_type text not null default 'general',
    address text,
    city text,
    state text,
    zipcode text,
    county text,
    latitude double precision,
    longitude double precision,
    phone text,
    website text,
    google_place_id text not null,
    google_rating numeric(3, 2),
    google_review_count integer,
    business_status text,
    primary_place_type text,
    place_types jsonb,
    source_state text,
    source_query text,
    data_source text not null default 'google_places',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists electrical_companies_google_place_id_idx
    on public.electrical_companies (google_place_id);

create index if not exists electrical_companies_state_city_idx
    on public.electrical_companies (state, city);

create index if not exists electrical_companies_type_idx
    on public.electrical_companies (electrician_type);

create index if not exists electrical_companies_brand_idx
    on public.electrical_companies (brand);

create index if not exists electrical_companies_source_state_idx
    on public.electrical_companies (source_state);

create or replace function public.set_electrical_companies_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists electrical_companies_set_updated_at on public.electrical_companies;

create trigger electrical_companies_set_updated_at
before update on public.electrical_companies
for each row
execute function public.set_electrical_companies_updated_at();

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.electrical_companies to anon, authenticated, service_role;
grant usage, select on sequence public.electrical_companies_company_id_seq to anon, authenticated, service_role;
